security:
    resource: "@SecurityBundle/Controller/"
    type:     annotation
    prefix:   /

tourism:
    resource: "@TourismBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
